<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CycleCount extends Model
{
    use HasFactory;

    protected $table = 'cycle_counts';

    protected $fillable = [
        'title',
        'user_id',
        'inv_adjustment',
        'sku_count',
        'category_1_title',
        'category_1_items',
        'category_1_amount',
        'category_2_title',
        'category_2_items',
        'category_2_amount',
        'category_3_title',
        'category_3_items',
        'category_3_amount',
        'category_4_title',
        'category_4_items',
        'category_4_amount',
        'category_5_title',
        'category_5_items',
        'category_5_amount',
        'category_6_title',
        'category_6_items',
        'category_6_amount',
        'category_7_title',
        'category_7_items',
        'category_7_amount',
        'category_8_title',
        'category_8_items',
        'category_8_amount',
        'category_9_title',
        'category_9_items',
        'category_9_amount',
        'category_10_title',
        'category_10_items',
        'category_10_amount',
        'category_11_title',
        'category_11_items',
        'category_11_amount',
        'category_12_title',
        'category_12_items',
        'category_12_amount',
        'category_13_title',
        'category_13_items',
        'category_13_amount',
        'category_14_title',
        'category_14_items',
        'category_14_amount',
        'category_15_title',
        'category_15_items',
        'category_15_amount',
        'category_16_title',
        'category_16_items',
        'category_16_amount',
        'category_17_title',
        'category_17_items',
        'category_17_amount',
        'category_18_title',
        'category_18_items',
        'category_18_amount',
        'category_19_title',
        'category_19_items',
        'category_19_amount',
        'category_20_title',
        'category_20_items',
        'category_20_amount',
        'category_21_title',
        'category_21_items',
        'category_21_amount',
        'category_22_title',
        'category_22_items',
        'category_22_amount',
        'category_23_title',
        'category_23_items',
        'category_23_amount',
        'category_24_title',
        'category_24_items',
        'category_24_amount',
        'category_25_title',
        'category_25_items',
        'category_25_amount',
        'category_26_title',
        'category_26_items',
        'category_26_amount',
        'category_27_title',
        'category_27_items',
        'category_27_amount',
        'category_28_title',
        'category_28_items',
        'category_28_amount',
    ];
}
